### ISSUE TITLE
The seondary dialog box is not appearing

### ISSUE THREAD

**Issue by lakshits11** [NabeelAhmed1721/vscode-rounded-ui#1]
After applying custom css, it is showing the primary suggestion box (the one shown just below when we type something) but I am ot shown the secondary one (the arrow marked)

![image](https://github.com/NabeelAhmed1721/vscode-rounded-ui/assets/54276661/678e7427-ab5f-475e-961e-12dfa9cca337)

**Comment by NabeelAhmed1721** [comment]
Hey,

I'm sorry you're having trouble. Can you provide me with more details?

The documentation box (the one the red arrow is pointing at) can be forced to open with <kbd>CTRL</kbd> + <kbd>SPACE</kbd>. Can you verify it still works?

Also, can you verify that you installed both `custom.css` *and* `custom.js`? They are both required to achieve the desired effect.

Thank you,
Nabeel Ahmed
